# Setup
title:               Rekabumi 
tagline:             'Blog hobi dan opini'
description:         ''
url:                 ''
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              seven
  url:               ''
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
